# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    Nord
# Repository: https://github.com/arcticicestudio/nord
# License:    MIT
# References:
#   https://circleci.com/docs/2.0
#   https://circleci.com/docs/2.0/circleci-images/#nodejs

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: preprocess-clean-node-modules
          command: rm -rf node_modules
      - run:
          name: preprocess-npm-install
          command: npm install
      - run:
          name: test
          command: npm run test
